jobs:
  include:
    - language: python
      python: 3.6
      services: postgres
      install:
        - pip install -r dev-requirements.txt
        - pip install -r requirements.txt
      script:
        - flake8 --statistics --verbose *.py
        - pytest -s src/test
